'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("UALiveBindingDemo.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EasyUAClient() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EasyUAClient", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to On a PointBinder, edit the BindingGroups collection, &quot;Add&quot; a new binding group, set its AutoRead property to True, and make sure that its AutoSubscribe property is set to False. 
        '''
        '''On a TextBox, use &quot;Bind to OPC-UA Data&quot; command and select the OPC-UA node you want to read. Then, use the &quot;Edit Live Bindings&quot; command, and set the BindingGroup property of the data binding to the binding group you have created earlier. The Read operation is automatically executed for all data bindings in this group when the fo [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Form1_automaticReadLinkLabel_LinkClicked_HelpText() As String
            Get
                Return ResourceManager.GetString("Form1_automaticReadLinkLabel_LinkClicked_HelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If you have not done so yet, drag the UAConnectivity component from the Toolbox to the form (this is a common step for all binding tasks). 
        '''
        '''Use the &quot;Bind to OPC-UA Data&quot; command on the target control, and select the source OPC-UA server and OPC node. 
        '''
        '''That&apos;s it. You can verify the result immediately, without recompiling your application, by using the &quot;Design Online&quot; command on the BindingExtender component..
        '''</summary>
        Friend ReadOnly Property Form1_automaticSubscriptionLinkLabel_LinkClicked_HelpText() As String
            Get
                Return ResourceManager.GetString("Form1_automaticSubscriptionLinkLabel_LinkClicked_HelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bind the OPC-UA data to your control as usually. 
        '''
        '''Then, use the &quot;Edit Live Bindings&quot; command on the control, and for the MappingKind property, select the kind of binding you want. .
        '''</summary>
        Friend ReadOnly Property Form1_bindingKindsLinkLabel_LinkClicked_HelpText() As String
            Get
                Return ResourceManager.GetString("Form1_bindingKindsLinkLabel_LinkClicked_HelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Drag the StatusToColorConverter component from the toolbox to the form. Bind the OPC-UA data to your control as usually. 
        '''
        '''Then, use the &quot;Edit Live Bindings&quot; command, &quot;Clone&quot; the existing binding, and change the cloned binding as follows: Set the MappingKind to StatusInfo. Set the ValueTarget.TargetMember to the BackColor (or other suitable) property of your control, and for the Converter property, select the StatusToColorConverter you have placed to the form earlier. This will cause the status informatio [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Form1_changeBackgroundLinkLabel_LinkClicked_HelpText() As String
            Get
                Return ResourceManager.GetString("Form1_changeBackgroundLinkLabel_LinkClicked_HelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to On a PointBinder, edit the BindingGroups collection, &quot;Add&quot; a new binding group, set its AutoSubscribe property to False, and set its WriteEventSource.SourceComponent to the button that should invoke the Write. 
        '''
        '''Drag the ErrorProvider extender (standard Microsoft component) from the toolbox to the form. 
        '''Configure the binding in a usual way. Use the &quot;Edit Live Bindings&quot; command, and for the MappingOperations options, select only &quot;Write&quot;, and set the BindingGroup property of the item binding to the bindin [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Form1_displayWriteErrorsLinkLabel_LinkClicked_HelpText() As String
            Get
                Return ResourceManager.GetString("Form1_displayWriteErrorsLinkLabel_LinkClicked_HelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Drag the ErrorProvider extender (standard Microsoft component) from the toolbox to the form. Configure the binding in a usual way. 
        '''
        '''Then, use the &quot;Edit Live Bindings&quot; command, &quot;Clone&quot; the existing binding, and change the cloned binding as follows: Set the MappingKind to ErrorMessage. Set the ValueTarget.ExtenderProvider to the ErrorProvider component on your form, and set the ValueTarget.TargetMember to the Error member. All in all, this will cause the error message from the OPC-UA be stored into the err [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Form1_errorProviderLinkLabel_LinkClicked_HelpText() As String
            Get
                Return ResourceManager.GetString("Form1_errorProviderLinkLabel_LinkClicked_HelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Drag the ToolTip extender (standard Microsoft component), or other extender provider you need, from the toolbox to the form. Configure the binding in a usual way. 
        '''Then, use the &quot;Edit Live Bindings&quot; command, &quot;Clone&quot; the existing binding, and change the cloned binding as follows: Set the ValueTarget.ExtenderProvider to the ToolTip (extender provider) component on your form, and set the ValueTarget.TargetMember to the Tooltip member. Set the MappingKind to AttributeData (or SourceTimestamp, ServerTimestamp,  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Form1_extendersLinkLabel_LinkClicked_HelpText() As String
            Get
                Return ResourceManager.GetString("Form1_extendersLinkLabel_LinkClicked_HelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to On a TextBox, use &quot;Bind to Point&quot; command and select the OPC-UA node you want to read (alternatively, use  &quot;Edit Live Bindings&quot; command, &quot;Add&quot; a PointBinding, and configure its EndpointDescriptor and NodeDescriptor). 
        '''
        '''Then, use the &quot;Edit Live Bindings&quot; command, and for MappingOperations property, leave just Read checked (and uncheck the Subscribe). In order to have the Read invoked when the button is pressed, set the ReadEventSource.SourceComponent to the Button control; the SourceMember of the ReadEvent [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Form1_readOnCustomEventLinkLabel_LinkClicked_HelpText() As String
            Get
                Return ResourceManager.GetString("Form1_readOnCustomEventLinkLabel_LinkClicked_HelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bind the OPC-UA node to the TextBox or similar control as usually. 
        '''
        '''Then, use the &quot;Edit Live Bindings&quot; command on the control, and set the StringFormat property on the data binding as needed, using all standard .NET formatting capabilities. {0} in the formatting string represents the value to be formatted. For example, {0:F3} means a floating point value formatted with 3 decimal places..
        '''</summary>
        Friend ReadOnly Property Form1_stringFormattingLinkLabel_LinkClicked_HelpText() As String
            Get
                Return ResourceManager.GetString("Form1_stringFormattingLinkLabel_LinkClicked_HelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to On the target control, use &quot;Bind to OPC-UA Data&quot; command and select the OPC-UA node you want to bind to. 
        '''Then, use the &quot;Edit Live Bindings&quot; command, and for MappingOperations property, add a check next to the Write operation. In order to have the Write invoked when the control changes, set the WriteEventSource.SourceComponent to your control; the SourceMember of the WriteEventSource will be automatically determined, but you can change it, if you want to link to a different event. 
        '''
        '''Note: Some controls o [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Form1_subscribeAndWriteLinkLabel_LinkClicked_HelpText() As String
            Get
                Return ResourceManager.GetString("Form1_subscribeAndWriteLinkLabel_LinkClicked_HelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to On a PointBinder, edit the BindingGroups collection, &quot;Add&quot; a new binding group, set its AutoSubscribe property to False, and set its WriteEventSource.SourceComponent to the button that should invoke the Write. 
        '''
        '''On each of the value controls involved, use &quot;Bind to OPC-UA Data&quot; command and select the OPC-UA node you want to write. Then, use the &quot;Edit Live Bindings&quot; command, and for the MappingOperations options, select only &quot;Write&quot;. Also, set the BindingGroup property of the data binding to the binding gro [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Form1_writeGroupLinkLabel_LinkClicked_HelpText() As String
            Get
                Return ResourceManager.GetString("Form1_writeGroupLinkLabel_LinkClicked_HelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to On a TextBox, use &quot;Bind to OPC-UA Data&quot; command and select the OPC-UA node want to write.
        ''' 
        '''Then, use the &quot;Edit Live Bindings&quot; command, and for the MappingOperations options, select only &quot;Write&quot;. In order to have the Write invoked when the button is pressed, set the WriteEventSource.SourceComponent to the Button control; the SourceMember of the WriteEventSource will be automatically set to the Click event. This causes the Click on the button execute the Write operation, i.e. obtain the value from the cont [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Form1_writeSingleLinkLabel_LinkClicked_HelpText() As String
            Get
                Return ResourceManager.GetString("Form1_writeSingleLinkLabel_LinkClicked_HelpText", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
